In [19]:
import pandas as pd
def romaneios_executados(caminho1, caminho2):
    romaneio_executado = pd.read_excel(caminho1, dtype={'ROMANEIO': str})
    romaneio_emitido = pd.read_excel(caminho2, dtype={'ROMANEIO': str})
    
   
    # Remove espaços em branco e preenche com zeros à esquerda para ter 6 dígitos
    romaneio_executado['ROMANEIO'] = romaneio_executado['ROMANEIO'].str.strip().str.zfill(6)
    romaneio_emitido['ROMANEIO'] = romaneio_emitido['ROMANEIO'].str.strip().str.zfill(6)
    
    #remove a 1 linha dos emitods
    romaneio_emitido.drop(0,axis=0, inplace=True)
    romaneio_executado.drop(0, axis=0, inplace=True)
    #cria a lista que para abrigar os dataframes sem valor
    
    lista_dataframes_sem_valor = []
    #função para comparar os romaneios e criar o documento de romaneio sem valor
    romaneios_sem_valor = {"ROMANEIOS_SEM_VALOR": [], "FILIAL":[]}
    for index, row in romaneio_emitido.iterrows():
        romaneio = row["ROMANEIO"]
        filial = row["EMISSORA"]
    
        if romaneio not in romaneio_executado["ROMANEIO"].values:
            print("OK")
            romaneios_sem_valor["ROMANEIOS_SEM_VALOR"].append(romaneio)
            romaneios_sem_valor["FILIAL"].append(filial)
    
    # Cria um DataFrame com os valores de ROMANEIO sem valor
    romaneio_sem_valor = pd.DataFrame(romaneios_sem_valor)
    romaneio_sem_valor['ROMANEIOS_SEM_VALOR'] = romaneio_sem_valor['ROMANEIOS_SEM_VALOR'].astype(str)
    # Remove espaços em branco e preenche com zeros à esquerda para ter 6 dígitos
    romaneio_sem_valor['ROMANEIOS_SEM_VALOR'] = romaneio_sem_valor['ROMANEIOS_SEM_VALOR'].astype(str).str.strip().str.zfill(6)
    
    lista_dataframes_sem_valor.append(romaneio_sem_valor)
    
    
    dataframe_auxiliar = romaneio_emitido[['ROMANEIO', 'FRT.AGREGADO APURADO']]
    dataframe_auxiliar.rename({'FRT.AGREGADO APURADO': "APURADO"})
    
    
    romaneio_final = pd.merge(romaneio_executado, dataframe_auxiliar, on="ROMANEIO",how="inner")
    
        
    romaneio_final["EMISSAO"] = pd.to_datetime(romaneio_final["EMISSAO"]) 
    romaneio_final["BAIXA"] = pd.to_datetime(romaneio_final["BAIXA"])

    romaneio_final['EMISSAO'] = romaneio_final['EMISSAO'].dt.strftime('%d/%m/%Y')
    romaneio_final['BAIXA'] = romaneio_final['BAIXA'].dt.strftime('%d/%m/%Y')
    
    
    return romaneio_final

caminho1 = "EXECUTADOS_MTO.xlsx"
caminho2 = "ROMANEIO_EMITIDOS_MTO.xlsx"
romaneios_executados(caminho1, caminho2)

OK

C:\Users\brito\anaconda3\Lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,FILIAL,ROMANEIO,EMISSAO,BAIXA,VEICULO,MOTORISTA,COLETA,ENTREGA,PESO(KG),VOLUMES,COLETA.1,ENTREGA.1,PESO(KG).1,PRODUTIVIDADE,FRT.AGREGADO APURADO
0,MTO,000112,01/03/2024,01/03/2024,PUF-9H59,IURE RAMIRES PACHECO,0.0,1.0,3293.277,25.0,0.0,1.0,3293.277,100.0,1000.0
1,MTO,000113,01/03/2024,01/03/2024,RCX-7E63,LUIZ ALEXANDRE PEREIRA,1.0,0.0,12096.000,1.0,1.0,0.0,12096.000,100.0,0.0
2,MTO,000114,04/03/2024,04/03/2024,MHA-6B40,SANDERSON FERREIRA TERRES,0.0,63.0,8453.015,106.0,0.0,63.0,8453.015,100.0,1800.0
3,MTO,000115,05/03/2024,05/03/2024,PIW-5A30,IURE RAMIRES PACHECO,0.0,1.0,290.085,18.0,0.0,1.0,290.085,100.0,1000.0
4,MTO,000116,05/03/2024,05/03/2024,RCS-7A30,JOSE BARBOZA DA SILVA,1.0,0.0,1509.600,6.0,1.0,0.0,1509.600,100.0,0.0
5,MTO,000117,11/03/2024,11/03/2024,RCS-7A30,JOSE BARBOZA DA SILVA,0.0,28.0,3055.090,51.0,0.0,28.0,3055.090,100.0,1800.0
6,MTO,000118,14/03/2024,14/03/2024,MHA-6B40,SANDERSON FERREIRA TERRES,1.0,0.0,2600.000,15.0,1.0,0.0,2600.000,100.0,0.0
7,MTO,000120,15/03/2024,15/03/2024,FJX-6346,SANDERSON FERREIRA TERRES,0.0,29.0,4626.234,39.0,0.0,29.0,4626.234,100.0,0.0
8,MTO,000122,18/03/2024,18/03/2024,PUF-9H59,IURE RAMIRES PACHECO,1.0,0.0,300.000,4.0,1.0,0.0,300.000,100.0,0.0
9,MTO,000123,19/03/2024,19/03/2024,FJX-6346,SANDERSON FERREIRA TERRES,1.0,0.0,8139.400,26.0,1.0,0.0,8139.400,100.0,0.0
10,MTO,000124,21/03/2024,21/03/2024,FJX-6346,SANDERSON FERREIRA TERRES,0.0,29.0,13138.320,108.0,0.0,29.0,13138.320,100.0,0.0
11,MTO,000125,25/03/2024,25/03/2024,FJX-6346,SANDERSON FERREIRA TERRES,0.0,17.0,6472.669,53.0,0.0,17.0,6472.669,100.0,0.0
12,MTO,000126,28/03/2024,28/03/2024,RCX-7E63,EDSON MULLER,0.0,2.0,416.000,5.0,0.0,2.0,416.000,100.0,0.0
13,MTO,000127,28/03/2024,28/03/2024,LLY-8853,MAYCON ALVES MACHADO,1.0,0.0,1008.000,7.0,1.0,0.0,1008.000,100.0,400.0

  ROMANEIOS_SEM_VALOR FILIAL
0              000121    MTO

,FILIAL,ROMANEIO,EMISSAO,BAIXA,VEICULO,MOTORISTA,COLETA,ENTREGA,PESO(KG),VOLUMES,COLETA.1,ENTREGA.1,PESO(KG).1,PRODUTIVIDADE,FRT.AGREGADO APURADO
0,MTO,000112,01/03/2024,01/03/2024,PUF-9H59,IURE RAMIRES PACHECO,0.0,1.0,3293.277,25.0,0.0,1.0,3293.277,100.0,1000.0
1,MTO,000113,01/03/2024,01/03/2024,RCX-7E63,LUIZ ALEXANDRE PEREIRA,1.0,0.0,12096.000,1.0,1.0,0.0,12096.000,100.0,0.0
2,MTO,000114,04/03/2024,04/03/2024,MHA-6B40,SANDERSON FERREIRA TERRES,0.0,63.0,8453.015,106.0,0.0,63.0,8453.015,100.0,1800.0
3,MTO,000115,05/03/2024,05/03/2024,PIW-5A30,IURE RAMIRES PACHECO,0.0,1.0,290.085,18.0,0.0,1.0,290.085,100.0,1000.0
4,MTO,000116,05/03/2024,05/03/2024,RCS-7A30,JOSE BARBOZA DA SILVA,1.0,0.0,1509.600,6.0,1.0,0.0,1509.600,100.0,0.0
5,MTO,000117,11/03/2024,11/03/2024,RCS-7A30,JOSE BARBOZA DA SILVA,0.0,28.0,3055.090,51.0,0.0,28.0,3055.090,100.0,1800.0
6,MTO,000118,14/03/2024,14/03/2024,MHA-6B40,SANDERSON FERREIRA TERRES,1.0,0.0,2600.000,15.0,1.0,0.0,2600.000,100.0,0.0
7,MTO,000120,15/03/2024,15/03/2024,FJX-6346,SANDERSON FERREIRA TERRES,0.0,29.0,4626.234,39.0,0.0,29.0,4626.234,100.0,0.0
8,MTO,000122,18/03/2024,18/03/2024,PUF-9H59,IURE RAMIRES PACHECO,1.0,0.0,300.000,4.0,1.0,0.0,300.000,100.0,0.0
9,MTO,000123,19/03/2024,19/03/2024,FJX-6346,SANDERSON FERREIRA TERRES,1.0,0.0,8139.400,26.0,1.0,0.0,8139.400,100.0,0.0
10,MTO,000124,21/03/2024,21/03/2024,FJX-6346,SANDERSON FERREIRA TERRES,0.0,29.0,13138.320,108.0,0.0,29.0,13138.320,100.0,0.0
11,MTO,000125,25/03/2024,25/03/2024,FJX-6346,SANDERSON FERREIRA TERRES,0.0,17.0,6472.669,53.0,0.0,17.0,6472.669,100.0,0.0
12,MTO,000126,28/03/2024,28/03/2024,RCX-7E63,EDSON MULLER,0.0,2.0,416.000,5.0,0.0,2.0,416.000,100.0,0.0
13,MTO,000127,28/03/2024,28/03/2024,LLY-8853,MAYCON ALVES MACHADO,1.0,0.0,1008.000,7.0,1.0,0.0,1008.000,100.0,400.0